# Compile options
VERBOSE=n
OPT=g
USE_NANO=y
SEMIHOST=n
USE_FPU=y

# Libraries
USE_LPCOPEN=y
USE_SAPI=y
USE_FREERTOS=y
FREERTOS_HEAP_TYPE=1

DEFINES+=SAPI_USE_INTERRUPTS
# Tell SAPI to use FreeRTOS SYSTICK
#DEFINES+=TICK_OVER_RTOS
SRC += $(wildcard $(PROGRAM_PATH_AND_NAME)/src/drivers/*.c)
SRC += $(wildcard $(PROGRAM_PATH_AND_NAME)/src/tareas/*.c)


